k8s_version: "1.35"
containerd_version: "1.7.11"
calico_version: "3.31.1"
pod_network_cidr: "172.16.0.0/22"
k8s_apt_repo: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/"
k8s_apt_key: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
docker_apt_repo: "https://download.docker.com/linux/ubuntu"
docker_apt_key: "https://download.docker.com/linux/ubuntu/gpg"
