---
- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Initialize Kubernetes master
  hosts: k8s_master
  become: true
  roles:
    - master

- name: Join workers to the cluster
  hosts: k8s_workers
  become: true
  roles:
    - worker
