all:
  children:
    k8s_master:
      hosts:
        master-1:
          ansible_host:
          ansible_user: ansible

    k8s_workers:
      hosts:
        worker-1:
          ansible_host:
          ansible_user: ansible