---
- name: Run init tasks
  ansible.builtin.import_tasks: init.yml
  when: vault_action == "init"

- name: Run unseal tasks
  ansible.builtin.import_tasks: unseal.yml
  when: vault_action == "unseal"

- name: Run configure tasks
  ansible.builtin.import_tasks: configure.yml
  when: vault_action == "configure"
