---
- name: Download Calico manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"
    dest: /tmp/calico.yaml
    mode: "0644"

- name: Apply Calico manifest
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml
  environment:
    KUBECONFIG: /home/ansible/.kube/config

- name: Wait for calico-node daemonset to be ready
  ansible.builtin.command: >
    kubectl rollout status daemonset/calico-node
    -n kube-system
    --timeout=300s
  environment:
    KUBECONFIG: /home/ansible/.kube/config
  changed_when: false
